### ISSUE TITLE
Taq-seq code

### ISSUE THREAD

**Issue by sr320** [mattgeorgephd/PSMFC-mytilus-byssus-pilot#2]
@mattgeorgephd is there tag-seq code available that @graceleuchtenberger can start working on?

**Comment by mattgeorgephd** [comment]
Deposited code used for triploid oyster tagseq here:

https://github.com/mattgeorgephd/PSMFC-mytilus-byssus-pilot/tree/9739699e847d293345b4e38f14ef06774852ceaa/tagseq/oyster-code

**Comment by graceleuchtenberger** [comment]
Thank you! I'll start playing around with it and the byssus tag-seq data.

**Comment by mattgeorgephd** [comment]
I think I completed the first few steps of the tagseq analysis (QC/trimming), but had to stop at the alignment step (no transcriptome yet). The files should be on RAVEN.

**Comment by graceleuchtenberger** [comment]
Okay great! Forgive my ignorance here though, what is RAVEN? I can also meet with Steven to start hashing out some stuff.

**Comment by mattgeorgephd** [comment]
Looks like Sam was able to give you access. We can set up a call and I can walk you through where everything is and how to get started on the alignment w/ RAVEN.
